spring.config.import=optional:file:.env.dev[.properties]

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASWORD}

spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai/v1

spring.ai.openai.model=openai/gpt-oss-120b
spring.ai.openai.chat.temperature=0.2

spring.ai.model.embedding=none
spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY:empty}
spring.ai.google.genai.embedding.text.model=gemini-embedding-001
spring.ai.google.genai.embedding.text.dimensions=1536

spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=1536
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE

logging.level.org.springframework.ai=DEBUG
logging.level.org.springframework.ai.vectorstore=DEBUG